### PR TITLE
A photo for Solus

### PR DESCRIPTION
**Pull request by samurilla**
I'm redoing the PR with a license.txt for Crags.png.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Good stuff thanks ! Mind if I merge as squashed? (1 commit)

**Comment by samurilla** [comment]
Sure. That removes that extra comments, right?

**Comment by samurilla** [comment]
Rather, it removes the other commits?

**Comment by ikeydoherty** [comment]
Yeah squashes it all into a single commit

**Comment by samurilla** [comment]
Yeah, definitely!

**Comment by j-atoms** [comment]
I would like to contribute some art. I am not up to speed on git. Can I just drop the file and info here in conversations? Thanks.

**Pull request merged**
