### PR TITLE
Uploaded/submitted an image taken for the backgrounds category

### PR DESCRIPTION
**Pull request by Schyken**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Very nice! :) So for us to accept artwork contributions, we need to know some things:

 - License of the artwork
 - A name for the image
 - Origin

**Comment by Schyken** [comment]
Thank you very much. I've never licensed anything before, so I'll get right on that. ;) Always a learning experience.

**Comment by Schyken** [comment]
[Twigonometry](http://schyken.deviantart.com/art/Twigonometry-681490406) by [Alan Diggs](http://schyken.deviantart.com) is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

Image name: Twigonometry

Origin/source: I, Alan Diggs, am the author of this work.

**Comment by Schyken** [comment]
[Twigonometry](http://schyken.deviantart.com/art/Twigonometry-681490406) by [Alan Diggs](http://schyken.deviantart.com) is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

Image name: Twigonometry

Origin/source: I, Alan Diggs, am the author of this work.

**Comment by ikeydoherty** [comment]
@Schyken mind if I merge this as a squashed PR?

**Comment by Schyken** [comment]
That would be great, please do.

**Pull request merged**
